# Orientation Averaging

Compare stiffness predictions for $[0/90]_S$, $[\pm 45]_S$ and $[0/\pm 45/09]_S$ for direction Mori-Tanaka calculations and using the orientation averaging method.

## Orientation Tensors

First we calculate the discrete orientation tensors.
$$
a_{ij} = \frac{1}{N}\sum p_i p_j
$$
$$
a_{ijkl} = \frac{1}{N}\sum p_i p_j p_k p_l
$$
We can calculate $p_i$ for each of the plies in this example

| Angle | $p_1$ | $p_2$| $p_3$ |
|-------|-------|------|-------|
| 0     | 1     |   0  |  0    |
| 45    | $\frac{\sqrt{2}}{2}$ | $\frac{\sqrt{2}}{2}$ | 0 |
| -45   | $\frac{\sqrt{2}}{2}$ | $-\frac{\sqrt{2}}{2}$ | 0 |
| 90    | 0     |   1  |  0    |

In [1]:
import numpy as np

def p(th,ph):
    """
    Calculate unit vector for spherical angles theta and phi
    """
    return (np.sin(th)*np.cos(ph),np.sin(th)*np.sin(ph),np.cos(th))

p_0 = p(np.pi/2,0)
p_45 = p(np.pi/2,np.pi/4)
p_m45 = p(np.pi/2,-np.pi/4)
p_90 = p(np.pi/2,np.pi/2)

#calculate second-order orientation tensors
a2_090 = np.zeros((3,3))
a2_pm45 = np.zeros((3,3))
a2_04590 = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        a2_090[i,j] = 0.5*(p_0[i]*p_0[j] + p_90[i]*p_90[j])
        a2_pm45[i,j] = 0.5*(p_45[i]*p_45[j] + p_m45[i]*p_m45[j])
        a2_04590[i,j] = 0.25*(p_0[i]*p_0[j] + p_45[i]*p_45[j] + p_m45[i]*p_m45[j] + p_90[i]*p_90[j])

#calculate fourth-order orientation tensors
a4_090 = np.zeros((3,3,3,3))
a4_pm45 = np.zeros((3,3,3,3))
a4_04590 = np.zeros((3,3,3,3))
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                a4_090[i,j,k,l] = 0.5*(p_0[i]*p_0[j]*p_0[k]*p_0[l] + p_90[i]*p_90[j]*p_90[k]*p_90[l])
                a4_pm45[i,j,k,l] = 0.5*(p_45[i]*p_45[j]*p_45[k]*p_45[l] + p_m45[i]*p_m45[j]*p_m45[k]*p_m45[l])
                a4_04590[i,j,k,l] = 0.25*(p_0[i]*p_0[j]*p_0[k]*p_0[l] + p_45[i]*p_45[j]*p_45[k]*p_45[l] + p_m45[i]*p_m45[j]*p_m45[k]*p_m45[l] + p_90[i]*p_90[j]*p_90[k]*p_90[l])
                
print "0/90 laminate: "
print np.round(a2_090,decimals=2)
print "+-45 laminate: " 
print np.round(a2_pm45,decimals=2)
print "0/+-45/90 laminate: " 
print np.round(a2_04590,decimals=2)

0/90 laminate: 
[[ 0.5  0.   0. ]
 [ 0.   0.5  0. ]
 [ 0.   0.   0. ]]
+-45 laminate: 
[[ 0.5  0.   0. ]
 [ 0.   0.5  0. ]
 [ 0.   0.   0. ]]
0/+-45/90 laminate: 
[[ 0.5  0.   0. ]
 [ 0.   0.5  0. ]
 [ 0.   0.   0. ]]


In [2]:
# for printing purposes, recast 4th-order tensor as 6x6
def tens2eng(tens):
    """
    returns 4th-order tensor in engineering notation
    """
    A = np.zeros((6,6))
    #mapping
    code = {0:(0,0),1:(1,1),2:(2,2),3:(1,2),4:(0,2),5:(0,1)}
    for i in range(6):
        for j in range(6):
            A[i,j] = tens[code[i][0],code[i][1],code[j][0],code[j][1]]
    return A

A4_090 = tens2eng(a4_090)
A4_pm45 = tens2eng(a4_pm45)
A4_04590 = tens2eng(a4_04590)
print "0/90 laminate: "
print np.round(A4_090,decimals=2)
print "+-45 laminate: " 
print np.round(A4_pm45,decimals=2)
print "0/+-45/90 laminate: " 
print np.round(A4_04590,decimals=2)

0/90 laminate: 
[[ 0.5  0.   0.   0.   0.   0. ]
 [ 0.   0.5  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0. ]]
+-45 laminate: 
[[ 0.25  0.25  0.    0.    0.    0.  ]
 [ 0.25  0.25  0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.25]]
0/+-45/90 laminate: 
[[ 0.38  0.12  0.    0.    0.    0.  ]
 [ 0.12  0.37  0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.12]]


## Mori-Tanaka

To calculate the orientation average, we first need to find the uni-directional properties using the Mori-Tanaka method.
We will use the same properties (stiffness, fiber length) as in the previuos example.

In [3]:
#rotation functions
def qij_x(theta):
    """
    rotation tensor about x-axis by some theta
    input: theta (angle in radians)
    output: qij (3x3 rotation tensor)
    """
    qij = np.array([[1,0,0],
                   [0,np.cos(theta),np.sin(theta)],
                   [0,-np.sin(theta),np.cos(theta)]])
    return qij

def qij_y(theta):
    """
    rotation tensor abo|ut y-axis by some theta
    input: theta (angle in radians)
    output: qij (3x3 rotation tensor)
    """
    qij = np.array([[np.cos(theta), 0, -np.sin(theta)],
                   [0,1,0],
                   [np.sin(theta),0,np.cos(theta)]])
    return qij

def qij_z(theta):
    """
    rotation tensor about z-axis by some theta
    input: theta (angle in radians)
    output: qij (3x3 rotation tensor)
    """
    qij = np.array([[np.cos(theta),np.sin(theta),0],
                   [-np.sin(theta),np.cos(theta),0],
                   [0,0,1]])
    return qij

def R_sigma(q):
    """
    rotation matrix for engineering notation given some rotation tensor, qij
    note: uses convention for sigma = [s11, s22, s33, s23, s13, s12]
    input: q (3x3 rotation tensor)
    output: R_s (6x6 rotation matrix)
    """
    R_s = np.array([[q[0,0]**2,q[0,1]**2,q[0,2]**2,2.*q[0,1]*q[0,2],2.*q[0,0]*q[0,2], 2.*q[0,0]*q[0,1]],
                       [q[1,0]**2,q[1,1]**2,q[1,2]**2,2.*q[1,1]*q[1,2],2.*q[1,0]*q[1,2], 2.*q[1,0]*q[1,1]],
                       [q[2,0]**2,q[2,1]**2,q[2,2]**2,2.*q[2,1]*q[2,2],2.*q[2,0]*q[2,2], 2.*q[2,0]*q[2,1]],
                       [q[1,0]*q[2,0], q[1,1]*q[2,1], q[1,2]*q[2,2],q[1,2]*q[2,1]+q[1,1]*q[2,2], q[1,2]*q[2,0]+q[1,0]*q[2,2], q[1,1]*q[2,0]+q[1,0]*q[2,1]],
                       [q[0,0]*q[2,0], q[0,1]*q[2,1], q[0,2]*q[2,2],q[0,2]*q[2,1]+q[0,1]*q[2,2], q[0,2]*q[2,0]+q[0,0]*q[2,2], q[0,1]*q[2,0]+q[0,0]*q[2,1]],
                       [q[0,0]*q[1,0], q[0,1]*q[1,1], q[0,2]*q[1,2],q[0,2]*q[1,1]+q[0,1]*q[1,2], q[0,2]*q[1,0]+q[0,0]*q[1,2], q[0,1]*q[1,0]+q[0,0]*q[1,1]]])
    return R_s

In [31]:
#Eshelby tensor calculations
nu_m = 0.40 #matrix poisson's ratio
s = 20. #fiber aspect ratio
I1 = (2.*s/(s**2.-1.)**1.5)*(s*(s**2.-1.)**.5-np.arccosh(s))
Q = 3./(8.*(1-nu_m))
R = (1.-2.*nu_m)/(8.*(1.-nu_m))
T = Q*(4.-3.*I1)/(3*(s**2.-1.))
I3 = 4.-2.*I1

S = np.zeros((6,6))
S[0,0] = Q + R*I1 + 0.75*T
S[1,1] = S[0,0]
S[2,2] = 4./3.*Q + R*I3 + 2.*s**2.*T
S[0,1] = Q/3. - R*I1 + 4.*T/3.
S[1,0] = S[0,1]
S[0,2] = -R*I1 - s**2*T
S[1,2] = S[0,2]
S[2,0] = -R*I3 - T
S[2,1] = S[2,0]
S[5,5] = Q/3 + R*I1 + T/4
S[3,3] = 2*R - I1*R/2 - (1+s**2)*T/2
S[4,4] = S[3,3]

#fiber/matrix stiffness matrices
Ef = 230. #GPa
nu_f = 0.2
Em = 3.8 #GPa
#nu_m defined above

Cf = np.zeros((6,6))
#isotropic fiber
#Cf[0:3,0:3] = nu_f*np.ones((3,3))
#Cf = Cf + (1.-2.*nu_f)*np.eye(6)
#Cf[3:,3:] = Cf[3:,3:]/2.
#Cf = Ef/((1.+nu_f)*(1.-2.*nu_f))*Cf

#orthotropic fiber
Ef1 = 230.
Ef2 = 15.
Ef3 = 15.
v1 = 0.2 #xy
v2 = .0125 #yz
v3 = 0.2 #xz
G1 = 9.
G2 = 5.
G3 = 9.
Sf = np.array([[1./Ef1, -v1/Ef1, -v3/Ef1, 0, 0, 0],
              [-v1/Ef1, 1./Ef2, -v2/Ef2, 0, 0, 0],
              [-v3/Ef1, -v2/Ef2, 1./Ef3, 0, 0, 0],
              [0, 0, 0, 1./(2*G2), 0, 0],
              [0, 0, 0, 0, 1./(2*G3), 0],
              [0, 0, 0, 0, 0, 1./(2*G1)]])
Cf = np.linalg.inv(Sf)

Cm = np.zeros((6,6))
Cm[0:3,0:3] = nu_m*np.ones((3,3))
Cm = Cm + (1.-2.*nu_m)*np.eye(6)
Cm[3:,3:] = Cm[3:,3:]/2.
Cm = Em/((1+nu_m)*(1.-2.*nu_m))*Cm

#rotate S to x-direction
Q1 = qij_y(np.pi/2)
R1 = R_sigma(Q1)
S1 = np.dot(R1,np.dot(S,R1.T))

#Eshelby strain concentration
vf = 0.15 #fiber volume fraction
A_e = np.linalg.inv(np.eye(6)+np.dot(np.dot(S1,np.linalg.inv(Cm)),Cf-Cm))
A_mt = np.dot(A_e,np.linalg.inv(vf*A_e+(1-vf)*np.eye(6)))

#uni-directional stiffness
C_uni = Cm + vf*np.dot(Cf-Cm,A_mt)
#rotate to z
C_uni = np.dot(R1,np.dot(C_uni,R1.T))
print np.round(C1,decimals=2)

[[  8.54   5.26   5.29   0.     0.     0.  ]
 [  5.26   8.54   5.29   0.     0.     0.  ]
 [  5.29   5.29  26.6    0.     0.     0.  ]
 [  0.     0.     0.     2.06   0.     0.  ]
 [  0.     0.     0.     0.     2.06   0.  ]
 [  0.     0.     0.     0.     0.     1.86]]


## Orientation Averaging

Now that we have the uni-directional stiffness matrix, we can use orientation averaging for the three laminate orientations we are considering.

In [24]:
def ornavg(C,A4,a2):
    B1 = C[0,0] + C[2,2] - 2*C[1,2] -4*C[4,4]
    B2 = C[1,2] - C[0,1]
    B3 = C[4,4] - 0.5*(C[0,0]-C[0,1])
    B4 = C[0,1]
    B5 = 0.5*(C[0,0]-C[0,1])
    #map between tensor and engineering notation
    code = {0:(0,0),1:(1,1),2:(2,2),3:(1,2),4:(0,2),5:(0,1)}
    C_avg = np.zeros((6,6))
    for i in range(6):
        for j in range(6):
            C_avg[i,j] = B1*A4[i,j] + B2*(
            a2[code[i][0],code[i][1]]*(code[j][0]==code[j][1]) + 
                a2[code[j][0],code[j][1]]*(code[i][0]==code[i][1])) + B3*(
            a2[code[i][0],code[j][0]]*(code[i][1]==code[j][1]) +
            a2[code[i][0],code[j][1]]*(code[i][1]==code[j][0]) +
            a2[code[i][1],code[j][0]]*(code[i][0]==code[j][1]) +
            a2[code[i][1],code[j][1]]*(code[i][0]==code[j][0])) + B4*(
            (code[i][0]==code[i][1])*(code[j][0]==code[j][1])) + B5*(
            (code[i][0]==code[j][0])*(code[i][1]==code[j][1]) +
            (code[i][0]==code[j][1])*(code[i][1]==code[j][0]))
    return C_avg
C_avg_090 = ornavg(C_uni,A4_090,a2_090)
C_avg_pm45 = ornavg(C_uni,A4_pm45,a2_pm45)
C_avg_04590 = ornavg(C_uni,A4_04590,a2_04590)
a2s = np.array([[0.95, 0, 0],
               [0,.05,0],
               [0,0,.05]])
a2c = np.eye(3)/3.

In [6]:
print np.round(C_avg_090,decimals=2)
print np.round(C_avg_pm45,decimals=2)
print np.round(C_avg_04590,decimals=2)

[[ 17.57   5.26   5.27   0.     0.     0.  ]
 [  5.26  17.57   5.27   0.     0.     0.  ]
 [  5.27   5.27  26.6    0.     0.     0.  ]
 [  0.     0.     0.     6.35   0.     0.  ]
 [  0.     0.     0.     0.     6.35   0.  ]
 [  0.     0.     0.     0.     0.     2.06]]
[[ 13.47   9.36   5.27   0.     0.     0.  ]
 [  9.36  13.47   5.27   0.     0.     0.  ]
 [  5.27   5.27  26.6    0.     0.     0.  ]
 [  0.     0.     0.     6.35   0.     0.  ]
 [  0.     0.     0.     0.     6.35   0.  ]
 [  0.     0.     0.     0.     0.     6.15]]
[[ 15.52   7.31   5.27   0.     0.     0.  ]
 [  7.31  15.52   5.27   0.     0.     0.  ]
 [  5.27   5.27  26.6    0.     0.     0.  ]
 [  0.     0.     0.     6.35   0.     0.  ]
 [  0.     0.     0.     0.     6.35   0.  ]
 [  0.     0.     0.     0.     0.     4.1 ]]


## Mori-Tanaka Oriented

Now we compare with the oriented Mori-Tanaka method, I'm pasting rotation code from the previous example below

In [7]:
def qij_x(theta):
    """
    rotation tensor about x-axis by some theta
    input: theta (angle in radians)
    output: qij (3x3 rotation tensor)
    """
    qij = np.array([[1,0,0],
                   [0,np.cos(theta),np.sin(theta)],
                   [0,-np.sin(theta),np.cos(theta)]])
    return qij

def qij_y(theta):
    """
    rotation tensor abo|ut y-axis by some theta
    input: theta (angle in radians)
    output: qij (3x3 rotation tensor)
    """
    qij = np.array([[np.cos(theta), 0, -np.sin(theta)],
                   [0,1,0],
                   [np.sin(theta),0,np.cos(theta)]])
    return qij

def qij_z(theta):
    """
    rotation tensor about z-axis by some theta
    input: theta (angle in radians)
    output: qij (3x3 rotation tensor)
    """
    qij = np.array([[np.cos(theta),np.sin(theta),0],
                   [-np.sin(theta),np.cos(theta),0],
                   [0,0,1]])
    return qij

def R_sigma(q):
    """
    rotation matrix for engineering notation given some rotation tensor, qij
    note: uses convention for sigma = [s11, s22, s33, s23, s13, s12]
    input: q (3x3 rotation tensor)
    output: R_s (6x6 rotation matrix)
    """
    R_s = np.array([[q[0,0]**2,q[0,1]**2,q[0,2]**2,2.*q[0,1]*q[0,2],2.*q[0,0]*q[0,2], 2.*q[0,0]*q[0,1]],
                       [q[1,0]**2,q[1,1]**2,q[1,2]**2,2.*q[1,1]*q[1,2],2.*q[1,0]*q[1,2], 2.*q[1,0]*q[1,1]],
                       [q[2,0]**2,q[2,1]**2,q[2,2]**2,2.*q[2,1]*q[2,2],2.*q[2,0]*q[2,2], 2.*q[2,0]*q[2,1]],
                       [q[1,0]*q[2,0], q[1,1]*q[2,1], q[1,2]*q[2,2],q[1,2]*q[2,1]+q[1,1]*q[2,2], q[1,2]*q[2,0]+q[1,0]*q[2,2], q[1,1]*q[2,0]+q[1,0]*q[2,1]],
                       [q[0,0]*q[2,0], q[0,1]*q[2,1], q[0,2]*q[2,2],q[0,2]*q[2,1]+q[0,1]*q[2,2], q[0,2]*q[2,0]+q[0,0]*q[2,2], q[0,1]*q[2,0]+q[0,0]*q[2,1]],
                       [q[0,0]*q[1,0], q[0,1]*q[1,1], q[0,2]*q[1,2],q[0,2]*q[1,1]+q[0,1]*q[1,2], q[0,2]*q[1,0]+q[0,0]*q[1,2], q[0,1]*q[1,0]+q[0,0]*q[1,1]]])
    return R_s

Now for the stiffness calculations

In [8]:
Q1 = qij_y(np.pi/2)
Q2_45 = qij_x(np.pi/4) #plus 45 rotation
Q2_m45 = qij_x(-np.pi/4) #minus 45 rotation
Q2_90 = qij_x(np.pi/2) #90 degrees

Q_45 = np.dot(Q1.T,Q2_45.T) #matrix multiplication in python
Q_m45 = np.dot(Q1.T,Q2_m45.T)
Q_0 = Q1.T
Q_90 = np.dot(Q1.T,Q2_90.T)

#engineering notation transformations for all 4 angles
R_45 = R_sigma(Q_45)
R_m45 = R_sigma(Q_m45)
R_90 = R_sigma(Q_0)
R_0 = R_sigma(Q_90)

#rotated Eshelby tensors
S_45 = np.dot(R_45,np.dot(S,R_45.T))
S_m45 = np.dot(R_m45,np.dot(S,R_m45.T))
S_0 = np.dot(R_0,np.dot(S,R_0.T))
S_90 = np.dot(R_90,np.dot(S,R_90.T))

#Eshelby strain concentration tensors
A_45 = np.linalg.inv(np.eye(6)+np.dot(np.dot(S_45,np.linalg.inv(Cm)),(Cf-Cm)))
A_m45 = np.linalg.inv(np.eye(6)+np.dot(np.dot(S_m45,np.linalg.inv(Cm)),(Cf-Cm)))
A_0 = np.linalg.inv(np.eye(6)+np.dot(np.dot(S_0,np.linalg.inv(Cm)),(Cf-Cm)))
A_90 = np.linalg.inv(np.eye(6)+np.dot(np.dot(S_90,np.linalg.inv(Cm)),(Cf-Cm)))

#Mori-Tanaka strain concentration tensors
#+- 45 laminate
v_m = 1-vf #matrix volume fraction
A_tot = A_45*vf/2 + A_m45*vf/2
A_mt_45 = np.dot(A_45,np.linalg.inv(A_tot+(1-vf)*np.eye(6)))
A_mt_m45 = np.dot(A_m45,np.linalg.inv(A_tot+(1-vf)*np.eye(6)))
C_mt_pm45 = Cm + vf/2*np.dot((Cf-Cm),A_mt_45) + vf/2*np.dot((Cf-Cm),A_mt_m45)

#0/90 laminate
A_tot = A_0*vf/2 + A_90*vf/2
A_mt_0 = np.dot(A_0,np.linalg.inv(A_tot+(1-vf)*np.eye(6)))
A_mt_90 = np.dot(A_90,np.linalg.inv(A_tot+(1-vf)*np.eye(6)))
C_mt_090 = Cm + vf/2*np.dot((Cf-Cm),A_mt_0) + vf/2*np.dot((Cf-Cm),A_mt_90)

#0/+-45/90 laminate
A_tot = A_0*vf/4 + A_90*vf/4 + A_45*vf/4 + A_m45*vf/4
A_mt_0 = np.dot(A_0,np.linalg.inv(A_tot+(1-vf)*np.eye(6)))
A_mt_90 = np.dot(A_90,np.linalg.inv(A_tot+(1-vf)*np.eye(6)))
A_mt_45 = np.dot(A_45,np.linalg.inv(A_tot+(1-vf)*np.eye(6)))
A_mt_m45 = np.dot(A_m45,np.linalg.inv(A_tot+(1-vf)*np.eye(6)))
C_mt_04590 = Cm + vf/4*np.dot((Cf-Cm),A_mt_0) + vf/4*np.dot((Cf-Cm),A_mt_90) + vf/4*np.dot((Cf-Cm),A_mt_45) + vf/4*np.dot((Cf-Cm),A_mt_m45)

In [9]:
print np.round(C_avg_090,decimals=2)
print np.round(C_mt_090,decimals=2)

print np.round(C_avg_pm45,decimals=2)
print np.round(C_mt_pm45,decimals=2)

print np.round(C_avg_04590,decimals=2)
print np.round(C_mt_04590,decimals=2)

[[ 17.57   5.26   5.27   0.     0.     0.  ]
 [  5.26  17.57   5.27   0.     0.     0.  ]
 [  5.27   5.27  26.6    0.     0.     0.  ]
 [  0.     0.     0.     6.35   0.     0.  ]
 [  0.     0.     0.     0.     6.35   0.  ]
 [  0.     0.     0.     0.     0.     2.06]]
[[ 18.41   5.23   5.51   0.     0.     0.  ]
 [  5.22   8.74   5.1    0.     0.     0.  ]
 [  5.51   5.1    8.66   0.     0.     0.  ]
 [  0.     0.     0.     1.89   0.     0.  ]
 [  0.     0.     0.     0.     2.02   0.  ]
 [  0.     0.     0.     0.     0.     2.06]]
[[ 13.47   9.36   5.27   0.     0.     0.  ]
 [  9.36  13.47   5.27   0.     0.     0.  ]
 [  5.27   5.27  26.6    0.     0.     0.  ]
 [  0.     0.     0.     6.35   0.     0.  ]
 [  0.     0.     0.     0.     6.35   0.  ]
 [  0.     0.     0.     0.     0.     6.15]]
[[ 9.83  5.71  5.32  0.    0.    0.  ]
 [ 5.71  8.68  5.14  0.    0.    0.  ]
 [ 5.32  5.14  8.64  0.    0.    0.  ]
 [ 0.    0.    0.    1.89  0.    0.  ]
 [ 0.    0.    0.    0.    2.02

## Closure Approximations

Since all closure approximations use the second-order orientation tensor, we will get the same prediction for any of these laminates.
We will compare three simple closure methods, the linear, quadratic, and hybrid methods


In [34]:
#linear closure
a2 = a2c
a4_l = np.zeros((3,3,3,3))
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                a4_l[i,j,k,l] = -1./24.*((i==j)*(k==l) + (i==k)*(j==l) + (i==l)*(j==k)) + 1./6.*(
                a2[i,j]*(k==l) + a2[i,k]*(j==l) +a2[i,l]*(j==k) + a2[k,l]*(i==j) + 
                a2[j,l]*(i==k) + a2[j,k]*(i==l))
A4_l = tens2eng(a4_l)
C_l = ornavg(C_uni,A4_l,a2)

#quadratic closure
a4_q = np.zeros((3,3,3,3))
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                a4_q[i,j,k,l] = a2[i,j]*a2[k,l]
A4_q = tens2eng(a4_q)
C_q = ornavg(C_uni, A4_q,a2)

#hybrid closure
f = -0.5
for i in range(3):
    for j in range(3):
        f = f + 1.5*a2[i,j]*a2[j,i]
A4_h = (1-f)*A4_l + f*A4_q
C_h = ornavg(C_uni,A4_h,a2)

In [35]:
#print np.round(C_l,decimals=2)
#print np.round(C_q,decimals=2)
print np.round(C_h,decimals=2)

[[ 12.52   6.41   6.41   0.     0.     0.  ]
 [  6.41  12.52   6.41   0.     0.     0.  ]
 [  6.41   6.41  12.52   0.     0.     0.  ]
 [  0.     0.     0.     3.05   0.     0.  ]
 [  0.     0.     0.     0.     3.05   0.  ]
 [  0.     0.     0.     0.     0.     3.05]]


In [12]:
f

5.624099184981966e-33

The hybrid method assumes this is a fairly random distribution ($f=0$), and thus converges to the linear closure.

In [13]:
C_z = np.array([[8.53,5.64,5.62,0,0,0],
                [5.64,8.53,5.62,0,0,0],
                [5.65,5.65,9.35,0,0,0],
                [0,0,0,1.56,0,0],
                [0,0,0,0,1.56,0],
                [0,0,0,0,0,1.53]])
a_rand = np.array([[0.333,0,0],
                  [0,0.333,0],
                  [0,0,0.333]])
a2=a_rand
a4_l = np.zeros((3,3,3,3))
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                a4_l[i,j,k,l] = -1./24.*((i==j)*(k==l) + (i==k)*(j==l) + (i==l)*(j==k)) + 1./6.*(
                a2[i,j]*(k==l) + a2[i,k]*(j==l) +a2[i,l]*(j==k) + a2[k,l]*(i==j) + 
                a2[j,l]*(i==k) + a2[j,k]*(i==l))
A4_l = tens2eng(a4_l)
C_l = ornavg(C_z,A4_l,a2)

#quadratic closure
a4_q = np.zeros((3,3,3,3))
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                a4_q[i,j,k,l] = a2[i,j]*a2[k,l]
A4_q = tens2eng(a4_q)
C_q = ornavg(C_z, A4_q,a2)

#hybrid closure
f = -1.0
for i in range(3):
    for j in range(3):
        f = f + 2*a2[i,j]*a2[j,i]
A4_h = (1-f)*A4_l + f*A4_q
C_h = ornavg(C_z,A4_h,a2)
print np.round(C_l,decimals=2)
print np.round(C_q,decimals=2)
print np.round(C_h,decimals=2)

[[ 8.75  5.65  5.65  0.    0.    0.  ]
 [ 5.65  8.75  5.65  0.    0.    0.  ]
 [ 5.65  5.65  8.75  0.    0.    0.  ]
 [ 0.    0.    0.    1.55  0.    0.  ]
 [ 0.    0.    0.    0.    1.55  0.  ]
 [ 0.    0.    0.    0.    0.    1.55]]
[[ 8.71  5.67  5.67  0.    0.    0.  ]
 [ 5.67  8.71  5.67  0.    0.    0.  ]
 [ 5.67  5.67  8.71  0.    0.    0.  ]
 [ 0.    0.    0.    1.52  0.    0.  ]
 [ 0.    0.    0.    0.    1.52  0.  ]
 [ 0.    0.    0.    0.    0.    1.52]]
[[ 8.77  5.65  5.65  0.    0.    0.  ]
 [ 5.65  8.77  5.65  0.    0.    0.  ]
 [ 5.65  5.65  8.77  0.    0.    0.  ]
 [ 0.    0.    0.    1.56  0.    0.  ]
 [ 0.    0.    0.    0.    1.56  0.  ]
 [ 0.    0.    0.    0.    0.    1.56]]


In [14]:
f

-0.33466599999999991

In [15]:
#linear closure
a2 = np.array([[0, 0, 0],[0,0, 0],[0,0,1]])
a4_l = np.zeros((3,3,3,3))
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                a4_l[i,j,k,l] = -1./24.*((i==j)*(k==l) + (i==k)*(j==l) + (i==l)*(j==k)) + 1./6.*(
                a2[i,j]*(k==l) + a2[i,k]*(j==l) +a2[i,l]*(j==k) + a2[k,l]*(i==j) + 
                a2[j,l]*(i==k) + a2[j,k]*(i==l))
A4_l = tens2eng(a4_l)
C_l = ornavg(C_uni,A4_l,a2)

#quadratic closure
a4_q = np.zeros((3,3,3,3))
for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                a4_q[i,j,k,l] = a2[i,j]*a2[k,l]
A4_q = tens2eng(a4_q)
C_q = ornavg(C_uni, A4_q,a2)

#hybrid closure
f = -1.0
for i in range(3):
    for j in range(3):
        f = f + 2*a2[i,j]*a2[j,i]
A4_h = (1-f)*A4_l + f*A4_q
C_h = ornavg(C_uni,A4_h,a2)

In [16]:
np.round(C_l,decimals=2)

array([[ 24.55,   4.61,   7.31,   0.  ,   0.  ,   0.  ],
       [  4.61,  24.55,   7.31,   0.  ,   0.  ,   0.  ],
       [  7.31,   7.31,   6.49,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   4.1 ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   4.1 ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   9.97]])

In [17]:
np.round(C_q,decimals=2)

array([[ 26.6 ,   5.29,   5.26,   0.  ,   0.  ,   0.  ],
       [  5.29,  26.6 ,   5.26,   0.  ,   0.  ,   0.  ],
       [  5.26,   5.26,   8.54,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   2.06,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   2.06,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  10.65]])

In [18]:
np.round(C_h,decimals=2)

array([[ 26.6 ,   5.29,   5.26,   0.  ,   0.  ,   0.  ],
       [  5.29,  26.6 ,   5.26,   0.  ,   0.  ,   0.  ],
       [  5.26,   5.26,   8.54,   0.  ,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   2.06,   0.  ,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   2.06,   0.  ],
       [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,  10.65]])